---
- hosts: 172.31.20.232
  become: true
  tasks:
    - debug:
        msg: "{{image_name}}"
    - name: Pull default Docker image
      docker_image:
        name: "{{image_name}}"
        source: pull

    - name: Create default containers
      docker_container:
        name: dash
        image: "{{image_name}}"
        published_ports:
          - "80:80"
        state: started
        detach: yes

